name: visits_tracker
description: A Route-to-Market Sales Force Automation app for tracking customer visits
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Navigation
  go_router: ^12.1.1
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Offline Support
  connectivity_plus: ^5.0.1
  
  # UI Components
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Location
  geolocator: ^10.1.0
  
  # Timezone
  timezone: ^0.9.4
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.1.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
